### ISSUE TITLE
Multiple form

### ISSUE THREAD

**Issue by polikin** [Colourity/Fort.js#13]
It is possible to use it with multiple form?

http://jsfiddle.net/gy4akyxv/

**Comment by idrisk** [comment]
Seems simple enough. Will you be using two bars, or do you just want one?

**Comment by polikin** [comment]
Two bar. One per form.

**Comment by idrisk** [comment]
I hope [this](http://jsfiddle.net/6huamer7/) is good enough for you. All I did was create a new function and edit in the class names, then called both of them. It's pretty self explanatory once you look at it.

**Comment by polikin** [comment]
Thanks!
